<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <Content Remove="Pages\HRDash\Index.cshtml" />
    <Content Remove="wwwroot\js\print.js" />
  </ItemGroup>
  <ItemGroup>
    <_ContentIncludedByDefault Remove="Pages\HRDash\Index.cshtml" />
    <_ContentIncludedByDefault Remove="wwwroot\js\print.js" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="EPPlus" Version="8.0.8" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Negotiate" Version="8.0.6" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.6" />  
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.6" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.11">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="8.0.7" />
    <PackageReference Include="System.Data.SqlClient" Version="4.9.0" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Pages\EmployeeService\" />
    <Folder Include="TempStore\" />
    <Folder Include="wwwroot\assets\" />
    <Folder Include="wwwroot\lib\select2\" />
  </ItemGroup>
  <ItemGroup>
    <None Include="Pages\HRDash\Index.cshtml" />
    <None Include="wwwroot\js\print.js" />
    <None Include="wwwroot\js\select2\i18n\af.js" />
    <None Include="wwwroot\js\select2\i18n\ar.js" />
    <None Include="wwwroot\js\select2\i18n\az.js" />
    <None Include="wwwroot\js\select2\i18n\bg.js" />
    <None Include="wwwroot\js\select2\i18n\bn.js" />
    <None Include="wwwroot\js\select2\i18n\bs.js" />
    <None Include="wwwroot\js\select2\i18n\ca.js" />
    <None Include="wwwroot\js\select2\i18n\cs.js" />
    <None Include="wwwroot\js\select2\i18n\da.js" />
    <None Include="wwwroot\js\select2\i18n\de.js" />
    <None Include="wwwroot\js\select2\i18n\dsb.js" />
    <None Include="wwwroot\js\select2\i18n\el.js" />
    <None Include="wwwroot\js\select2\i18n\en.js" />
    <None Include="wwwroot\js\select2\i18n\eo.js" />
    <None Include="wwwroot\js\select2\i18n\es.js" />
    <None Include="wwwroot\js\select2\i18n\et.js" />
    <None Include="wwwroot\js\select2\i18n\eu.js" />
    <None Include="wwwroot\js\select2\i18n\fa.js" />
    <None Include="wwwroot\js\select2\i18n\fi.js" />
    <None Include="wwwroot\js\select2\i18n\fr.js" />
    <None Include="wwwroot\js\select2\i18n\gl.js" />
    <None Include="wwwroot\js\select2\i18n\he.js" />
    <None Include="wwwroot\js\select2\i18n\hi.js" />
    <None Include="wwwroot\js\select2\i18n\hr.js" />
    <None Include="wwwroot\js\select2\i18n\hsb.js" />
    <None Include="wwwroot\js\select2\i18n\hu.js" />
    <None Include="wwwroot\js\select2\i18n\hy.js" />
    <None Include="wwwroot\js\select2\i18n\id.js" />
    <None Include="wwwroot\js\select2\i18n\is.js" />
    <None Include="wwwroot\js\select2\i18n\it.js" />
    <None Include="wwwroot\js\select2\i18n\ja.js" />
    <None Include="wwwroot\js\select2\i18n\ka.js" />
    <None Include="wwwroot\js\select2\i18n\km.js" />
    <None Include="wwwroot\js\select2\i18n\ko.js" />
    <None Include="wwwroot\js\select2\i18n\lt.js" />
    <None Include="wwwroot\js\select2\i18n\lv.js" />
    <None Include="wwwroot\js\select2\i18n\mk.js" />
    <None Include="wwwroot\js\select2\i18n\ms.js" />
    <None Include="wwwroot\js\select2\i18n\nb.js" />
    <None Include="wwwroot\js\select2\i18n\ne.js" />
    <None Include="wwwroot\js\select2\i18n\nl.js" />
    <None Include="wwwroot\js\select2\i18n\pa.js" />
    <None Include="wwwroot\js\select2\i18n\pl.js" />
    <None Include="wwwroot\js\select2\i18n\ps.js" />
    <None Include="wwwroot\js\select2\i18n\pt-BR.js" />
    <None Include="wwwroot\js\select2\i18n\pt.js" />
    <None Include="wwwroot\js\select2\i18n\ro.js" />
    <None Include="wwwroot\js\select2\i18n\ru.js" />
    <None Include="wwwroot\js\select2\i18n\sk.js" />
    <None Include="wwwroot\js\select2\i18n\sl.js" />
    <None Include="wwwroot\js\select2\i18n\sq.js" />
    <None Include="wwwroot\js\select2\i18n\sr-Cyrl.js" />
    <None Include="wwwroot\js\select2\i18n\sr.js" />
    <None Include="wwwroot\js\select2\i18n\sv.js" />
    <None Include="wwwroot\js\select2\i18n\te.js" />
    <None Include="wwwroot\js\select2\i18n\th.js" />
    <None Include="wwwroot\js\select2\i18n\tk.js" />
    <None Include="wwwroot\js\select2\i18n\tr.js" />
    <None Include="wwwroot\js\select2\i18n\uk.js" />
    <None Include="wwwroot\js\select2\i18n\vi.js" />
    <None Include="wwwroot\js\select2\i18n\zh-CN.js" />
    <None Include="wwwroot\js\select2\i18n\zh-TW.js" />
  </ItemGroup>
  <ItemGroup>
    <UpToDateCheckInput Remove="Pages\HRDash\Index.cshtml" />
  </ItemGroup>
</Project>